from app.models.state import AgentState
from langchain_ollama import ChatOllama
import os

ollama_base_url = os.getenv("OLLAMA_HOST", "http://localhost:11434")
llm = ChatOllama(
    model="qwen2.5:7b",
    base_url=ollama_base_url,
    temperature=0
)


async def run(state: AgentState) -> AgentState:
    shap_factors = []
    if state.external_data and "shap_factors" in state.external_data:
        shap_factors = state.external_data["shap_factors"]

    shap_text = ", ".join(shap_factors) if shap_factors else "No SHAP factors available"
    reason_text = " | ".join(state.reasons) if state.reasons else "None"

    prompt = f"""
You are a senior credit risk explainer. Your job is to translate mathematical machine learning outputs into a clear, concise report for a human underwriter.

Applicant Data:
- Final Decision: {state.final_decision}
- Risk Score (Probability of Default): {state.risk_score}
- Supervisor Reasons: {reason_text}

Machine Learning SHAP values (Top Risk Drivers):
{shap_text}
*(Note for you: Positive SHAP values mean the feature increased the risk of default.

Task:
Write a brief, professional paragraph explaining exactly WHY this application received its final decision.
Explicitly mention the SHAP factors and explain how they impacted the risk score in plain, business-friendly English.
Do not use complex ML jargon like 'SHAP', just explain the impact.
"""
    response = await llm.ainvoke(prompt)
    explanation = response.content.strip()

    state.logs.append("SHAP-based Explainability Report Generated by LLM")
    state.policy_flags.append(f"AI explanation: \n{explanation}")

    return state